### PR TITLE
Merge updates on develop into master

### PR DESCRIPTION
**Pull request by rockivist**
@tcatapano I've done a fair amount of work to address issues #48, #51, #20, and #40.

Can you look over my changes, test them yourself, and if they past muster, merge them into the master branch and create a new release? 

As you'll see I've broken out schema-valid migration from dtd-valid migration, as well as breaking out undeprecated migration. So there are now four different version of the migration style sheet. 

Now that we are handling DTD migration separately, would it be possible for you to look into #32? The other remaining open issues are likely to remain so as documentation. I don't think there's anything to be done about them. But I suspect you may be able to address the entity migration.

Let me know if you want to chat about this. No particular deadline, but if you have time, I'd appreciate your assistance. As far as I'm concerned this closes my book on EAD3.

Mike

### CODE REVIEW

**Comment by tcatapano** [comment]
Testing EAD2002ToEAD3dtd.xsl against set of 2329 dtd valid EAD 2002 instances. Errors mostly in source. Probably ready to merge to master.

valid: 1666 (71.53%)
invalid: 663 (28.46%)

Errors:
- 611  Value "iso639-2" for attribute langencoding of control is not among the enumerated set _[Data error]_
- 107  Element scopecontent content does not follow the DTD, expecting (head? , (chronlist | list | table | blockquote | p | scopecontent)+), got () _[removal of dao leaves scopecontent empty]_
- 32  Syntax of value for attribute certainty of unitdate is not valid [value is null]
- 10  Element controlaccess content does not follow the DTD, expecting (head? , (chronlist | list | table | blockquote | p | persname | corpname | famname | geogname | name | occupation | subject | genreform | function | title | controlaccess)+), got () _[empty controlaccess in source]_
- 7  Element title is not declared in physdesc list of possible children _[unusual encoding in source]_
- 6  Element origination content does not follow the DTD, expecting (corpname | famname | name | persname)+, got () _[no *name elements in source; addressed by comment " PORTIONS NOT INCLUDED IN  persname, corpname, famname, OR name ELEMENTS WERE LOST."]_
- 3  Value "iso3166-a" for attribute countryencoding of control is not among the enumerated set _[data error]_
- 2  Element indexentry content does not follow the DTD, expecting ((namegrp | persname | corpname | famname | geogname | name | occupation | subject | genreform | function | title) , (ptrgrp | ptr | ref)? , indexentry*), got (ptr ) _[indexentry elements with no content; problem from template]_
- 1  Value "iso_639" for attribute langencoding of control is not among the enumerated set _[data error]_
- 1  Value "iso6392-b" for attribute langencoding of control is not among the enumerated set _[data_error]_
- 1  Value "iso155511" for attribute repositoryencoding of control is not among the enumerated set _[data error]_
- 1  Syntax of value for attribute certainty of date is not valid _[not in source]_
- 1  Element did content does not follow the DTD, expecting (head? , (abstract | container | dao | daoset | didnote | langmaterial | materialspec | origination | physdescset | physdesc | physdescstructured | physloc | repository | unitdate | unitdatestructured | unitid | unittitle)+), got _[did with note only, now empty after move to odd ]_

**Comment by rockivist** [comment]
Looks good to me. Not sure what we could have done about any of those errors.

Are you looking at the other style sheets?

**Comment by tcatapano** [comment]
Yes, I'm testing the schema one now. Many more problems there for some
reason... After that the undeprecated stylesheets.

/Terry

**Comment by tcatapano** [comment]
Testing EAD2002ToEAD3schema against 1412 EAD 2002 schema valid instances

XSD using Xerces in oXygen 18 (Linux):

1404 valid (99.4%)
8 invalid (.006%)

[XSD includeds ID/IDREF checking]
- 3 Description: cvc-complex-type.2.4.b: The content of element 'did' is not complete. One of '{"http://ead3.archivists.org/schema/":head, "http://ead3.archivists.org/schema/":abstract, "http://ead3.archivists.org/schema/":container, "http://ead3.archivists.org/schema/":dao, "http://ead3.archivists.org/schema/":daoset, "http://ead3.archivists.org/schema/":didnote, "http://ead3.archivists.org/schema/":langmaterial, "http://ead3.archivists.org/schema/":materialspec, "http://ead3.archivists.org/schema/":origination, "http://ead3.archivists.org/schema/":physdescset, "http://ead3.archivists.org/schema/":physdesc, "http://ead3.archivists.org/schema/":physdescstructured, "http://ead3.archivists.org/schema/":physloc, "http://ead3.archivists.org/schema/":repository, "http://ead3.archivists.org/schema/":unitdate, "http://ead3.archivists.org/schema/":unitdatestructured, "http://ead3.archivists.org/schema/":unitid, "http://ead3.archivists.org/schema/":unittitle}' is expected. _[note removed from did leaves did empty]_
-       2 Description: cvc-enumeration-valid: Value 'iso939' is not facet-valid with respect to enumeration '[iso639-1, iso639-2b, iso639-3, otherlangencoding]'. It must be a value from the enumeration. [data error]
-       2 Description: cvc-attribute.3: The value 'iso939' of attribute 'langencoding' on element 'control' is not valid with respect to its type, '#AnonType_langencodingcontrol'. _[data error]_
-       1 Description: cvc-id.1: There is no ID/IDREF binding for IDREF 'reprintsa2'. _[target element removed (extent)]_
-       1 Description: cvc-id.1: There is no ID/IDREF binding for IDREF 'manuscriptsa1'. _[target element removed (extent)]_
-       1 Description: cvc-id.1: There is no ID/IDREF binding for IDREF 'B1'. _[target element removed (extent)]_
-       1 Description: cvc-id.1: There is no ID/IDREF binding for IDREF 'A1'. _[target element removed (extent)]_
-       1 Description: cvc-complex-type.2.4.b: The content of element 'did' is not complete. One of '{"http://ead3.archivists.org/schema/":abstract, "http://ead3.archivists.org/schema/":container, "http://ead3.archivists.org/schema/":dao, "http://ead3.archivists.org/schema/":daoset, "http://ead3.archivists.org/schema/":didnote, "http://ead3.archivists.org/schema/":langmaterial, "http://ead3.archivists.org/schema/":materialspec, "http://ead3.archivists.org/schema/":origination, "http://ead3.archivists.org/schema/":physdescset, "http://ead3.archivists.org/schema/":physdesc, "http://ead3.archivists.org/schema/":physdescstructured, "http://ead3.archivists.org/schema/":physloc, "http://ead3.archivists.org/schema/":repository, "http://ead3.archivists.org/schema/":unitdate, "http://ead3.archivists.org/schema/":unitdatestructured, "http://ead3.archivists.org/schema/":unitid, "http://ead3.archivists.org/schema/":unittitle}' is expected. _[note removed from did leaves did with only head]_
-       1 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/":ref}'. One of '{"http://ead3.archivists.org/schema/":abbr, "http://ead3.archivists.org/schema/":expan, "http://ead3.archivists.org/schema/":emph, "http://ead3.archivists.org/schema/":lb, "http://ead3.archivists.org/schema/":ptr, "http://ead3.archivists.org/schema/":quote, "http://ead3.archivists.org/schema/":num, "http://ead3.archivists.org/schema/":footnote, "http://ead3.archivists.org/schema/":date, "http://ead3.archivists.org/schema/":persname, "http://ead3.archivists.org/schema/":corpname, "http://ead3.archivists.org/schema/":famname, "http://ead3.archivists.org/schema/":geogname, "http://ead3.archivists.org/schema/":name, "http://ead3.archivists.org/schema/":occupation, "http://ead3.archivists.org/schema/":subject, "http://ead3.archivists.org/schema/":genreform, "http://ead3.archivists.org/schema/":function, "http://ead3.archivists.org/schema/":title}' is expected. _[archref in p converted to ref, not valid as only child of p?]_
-       1 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/":footnote}'. One of '{"http://ead3.archivists.org/schema/":abbr, "http://ead3.archivists.org/schema/":emph, "http://ead3.archivists.org/schema/":expan, "http://ead3.archivists.org/schema/":foreign, "http://ead3.archivists.org/schema/":lb, "http://ead3.archivists.org/schema/":ptr, "http://ead3.archivists.org/schema/":ref}' is expected. _[note inside didnote converted to footnote]_

RelaxNG using jing in oXygen 18 (Linux)

1405 valid (99.5%)
7 invalid (.005%)

[RelaxNG does not peform ID/IDREF checking by default]
- 3 Description: element "did" incomplete; expected element "abstract", "container", "dao", "daoset", "didnote", "head", "langmaterial", "materialspec", "origination", "physdesc", "physdescset", "physdescstructured", "physloc", "repository", "unitdate", "unitdatestructured", "unitid" or "unittitle"  _[note removed from did leaves did empty]_
-       2 Description: value of attribute "langencoding" is invalid; must be equal to "iso639-1", "iso639-2b", "iso639-3" or "otherlangencoding" _[data error]_
-       1 Description: element "ref" not allowed here; expected the element end-tag, text or element "abbr", "corpname", "date", "emph", "expan", "famname", "footnote", "function", "genreform", "geogname", "lb", "name", "num", "occupation", "persname", "ptr", "quote", "subject" or "title"  _[archref in p converted to ref, not valid as only child of p?]_
-       1 Description: element "footnote" not allowed here; expected the element end-tag, text or element "abbr", "emph", "expan", "foreign", "lb", "ptr" or "ref" _[note inside didnote converted to footnote]_
-       1 Description: element "did" incomplete; expected element "abstract", "container", "dao", "daoset", "didnote", "langmaterial", "materialspec", "origination", "physdesc", "physdescset", "physdescstructured", "physloc", "repository", "unitdate", "unitdatestructured", "unitid" or "unittitle" _[note removed from did leaves did with only head]_

**Comment by tcatapano** [comment]
The results of the testing were very good. Most errors were either errors in the source or result of outlier practice (e.g., note as footnote inside note in did). One caveat is that the testbed was the same as the last time the conversion was tested. Testing against another randomly selected testbed might reveal previously undetected bugs.

**Comment by tcatapano** [comment]
Another caveat is that I havent tested the XSD validation using libxml2 due to the known bug in the definintion of objectxmlwrap. While I think this is a libxml problem rather than an EAD3 problem, it should be fixed since the libxml2 library is used by languages like Ruby (e.g., nokogiri) and Python (lxml, xml.etree).

**Comment by tcatapano** [comment]
@rockivist https://github.com/rockivist: should I find EAD2002 instances
with deprecated features to test the undeprecated stylesheets or should I
just test against the existing testbeds. The former will take much more
time.

**Comment by rockivist** [comment]
@tcatapano Just use the existing testbed. I want to make sure the schema and namespace stuff works and get it out. Easier to tweak the undeprecated-specific migration stuff later if we get bug reports.

**Comment by tcatapano** [comment]
Ok. Should definitely have this done by the end of the week.

**Comment by tcatapano** [comment]
Testing  EAD2002ToEAD3schema_undeprecated.xsl against schema-valid testbed (650 files)
 (using xerces in oXygen 18 Ubuntu 14.04)
- 346 Description: cvc-complex-type.3.2.2: Attribute 'type' is not allowed to appear in element 'physfacet'. _[seems like an error in stylesheet: see template at line 329. Copies source, should probably apply-templates]_
- 17 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/undeprecated/":imprint}'. One of '{"http://ead3.archivists.org/schema/undeprecated/":abbr, "http://ead3.archivists.org/schema/undeprecated/":expan, "http://ead3.archivists.org/schema/undeprecated/":emph, "http://ead3.archivists.org/schema/undeprecated/":lb, "http://ead3.archivists.org/schema/undeprecated/":ptr, "http://ead3.archivists.org/schema/undeprecated/":quote, "http://ead3.archivists.org/schema/undeprecated/":num, "http://ead3.archivists.org/schema/undeprecated/":footnote, "http://ead3.archivists.org/schema/undeprecated/":date, "http://ead3.archivists.org/schema/undeprecated/":persname, "http://ead3.archivists.org/schema/undeprecated/":corpname, "http://ead3.archivists.org/schema/undeprecated/":famname, "http://ead3.archivists.org/schema/undeprecated/":geogname, "http://ead3.archivists.org/schema/undeprecated/":name, "http://ead3.archivists.org/schema/undeprecated/":occupation, "http://ead3.archivists.org/schema/undeprecated/":subject, "http://ead3.archivists.org/schema/undeprecated/":genreform, "http://ead3.archivists.org/schema/undeprecated/":function, "http://ead3.archivists.org/schema/undeprecated/":title}' is expected. _[in schema imprint is allowed as child of bibref, but not as child of ref. Stylesheet wraps all children in ref. See template at line 435. Not clear whether this is a stylesheet or schema issue]_ 
- 12 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/undeprecated/":unitdate}'. One of '{"http://ead3.archivists.org/schema/undeprecated/":abbr, "http://ead3.archivists.org/schema/undeprecated/":emph, "http://ead3.archivists.org/schema/undeprecated/":expan, "http://ead3.archivists.org/schema/undeprecated/":foreign, "http://ead3.archivists.org/schema/undeprecated/":lb, "http://ead3.archivists.org/schema/undeprecated/":ptr, "http://ead3.archivists.org/schema/undeprecated/":ref, "http://ead3.archivists.org/schema/undeprecated/":date, "http://ead3.archivists.org/schema/undeprecated/":footnote, "http://ead3.archivists.org/schema/undeprecated/":num, "http://ead3.archivists.org/schema/undeprecated/":quote, "http://ead3.archivists.org/schema/undeprecated/":persname, "http://ead3.archivists.org/schema/undeprecated/":corpname, "http://ead3.archivists.org/schema/undeprecated/":famname, "http://ead3.archivists.org/schema/undeprecated/":geogname, "http://ead3.archivists.org/schema/undeprecated/":name, "http://ead3.archivists.org/schema/undeprecated/":occupation, "http://ead3.archivists.org/schema/undeprecated/":subject, "http://ead3.archivists.org/schema/undeprecated/":genreform, "http://ead3.archivists.org/schema/undeprecated/":function, "http://ead3.archivists.org/schema/undeprecated/":title, "http://ead3.archivists.org/schema/undeprecated/":list}' is expected. _[unittitle in item removed but child unitdate not removed. Pretty sure this has to do with the logic at line 1381 which has the unitdate[parent::unittitle] copied. ]_
- 3 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/undeprecated/":bibseries}'. One of '{"http://ead3.archivists.org/schema/undeprecated/":abbr, "http://ead3.archivists.org/schema/undeprecated/":expan, "http://ead3.archivists.org/schema/undeprecated/":emph, "http://ead3.archivists.org/schema/undeprecated/":lb, "http://ead3.archivists.org/schema/undeprecated/":ptr, "http://ead3.archivists.org/schema/undeprecated/":quote, "http://ead3.archivists.org/schema/undeprecated/":num, "http://ead3.archivists.org/schema/undeprecated/":footnote, "http://ead3.archivists.org/schema/undeprecated/":date, "http://ead3.archivists.org/schema/undeprecated/":persname, "http://ead3.archivists.org/schema/undeprecated/":corpname, "http://ead3.archivists.org/schema/undeprecated/":famname, "http://ead3.archivists.org/schema/undeprecated/":geogname, "http://ead3.archivists.org/schema/undeprecated/":name, "http://ead3.archivists.org/schema/undeprecated/":occupation, "http://ead3.archivists.org/schema/undeprecated/":subject, "http://ead3.archivists.org/schema/undeprecated/":genreform, "http://ead3.archivists.org/schema/undeprecated/":function, "http://ead3.archivists.org/schema/undeprecated/":title}' is expected.  _[same issue as with imprint above, in schema bibseries is allowed as child of bibref, but not as child of ref. Stylesheet wraps all children in ref. See template at line 435. Not clear whether this is a stylesheet or schema issue]_
- 2 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/undeprecated/":ref}'. One of '{"http://ead3.archivists.org/schema/undeprecated/":abbr, "http://ead3.archivists.org/schema/undeprecated/":expan, "http://ead3.archivists.org/schema/undeprecated/":emph, "http://ead3.archivists.org/schema/undeprecated/":lb, "http://ead3.archivists.org/schema/undeprecated/":ptr, "http://ead3.archivists.org/schema/undeprecated/":quote, "http://ead3.archivists.org/schema/undeprecated/":num, "http://ead3.archivists.org/schema/undeprecated/":footnote, "http://ead3.archivists.org/schema/undeprecated/":date, "http://ead3.archivists.org/schema/undeprecated/":persname, "http://ead3.archivists.org/schema/undeprecated/":corpname, "http://ead3.archivists.org/schema/undeprecated/":famname, "http://ead3.archivists.org/schema/undeprecated/":geogname, "http://ead3.archivists.org/schema/undeprecated/":name, "http://ead3.archivists.org/schema/undeprecated/":occupation, "http://ead3.archivists.org/schema/undeprecated/":subject, "http://ead3.archivists.org/schema/undeprecated/":genreform, "http://ead3.archivists.org/schema/undeprecated/":function, "http://ead3.archivists.org/schema/undeprecated/":title}' is expected. _ [same issue as with imprint above, in schema ref is allowed as child of bibref, but not as child of ref. Stylesheet wraps all children in ref. See template at line 435. Not clear whether this is a stylesheet or schema issue]_
- 1 Description: cvc-enumeration-valid: Value 'iso939' is not facet-valid with respect to enumeration '[iso639-1, iso639-2b, iso639-3, otherlangencoding]'. It must be a value from the enumeration. _[data error]_
- 1 Description: cvc-complex-type.2.4.b: The content of element 'did' is not complete. One of '{"http://ead3.archivists.org/schema/undeprecated/":head, "http://ead3.archivists.org/schema/undeprecated/":abstract, "http://ead3.archivists.org/schema/undeprecated/":container, "http://ead3.archivists.org/schema/undeprecated/":dao, "http://ead3.archivists.org/schema/undeprecated/":daoset, "http://ead3.archivists.org/schema/undeprecated/":didnote, "http://ead3.archivists.org/schema/undeprecated/":langmaterial, "http://ead3.archivists.org/schema/undeprecated/":materialspec, "http://ead3.archivists.org/schema/undeprecated/":origination, "http://ead3.archivists.org/schema/undeprecated/":physdescset, "http://ead3.archivists.org/schema/undeprecated/":physdesc, "http://ead3.archivists.org/schema/undeprecated/":physdescstructured, "http://ead3.archivists.org/schema/undeprecated/":physloc, "http://ead3.archivists.org/schema/undeprecated/":repository, "http://ead3.archivists.org/schema/undeprecated/":unitdate, "http://ead3.archivists.org/schema/undeprecated/":unitdatestructured, "http://ead3.archivists.org/schema/undeprecated/":unitid, "http://ead3.archivists.org/schema/undeprecated/":unittitle}' is expected. _[note as only child of did in source moved to odd, leaving did with no children]_
- 1 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/undeprecated/":corpname}'. One of '{"http://ead3.archivists.org/schema/undeprecated/":publisher, "http://ead3.archivists.org/schema/undeprecated/":geogname, "http://ead3.archivists.org/schema/undeprecated/":date, "http://ead3.archivists.org/schema/undeprecated/":emph, "http://ead3.archivists.org/schema/undeprecated/":lb, "http://ead3.archivists.org/schema/undeprecated/":ptr}' is expected. _[corpname not allowed as child of imprint; publisher is allowed and was present in source. was converted to corpname/[@relator = 'publisher']_
- 1 Description: cvc-attribute.3: The value 'iso939' of attribute 'langencoding' on element 'control' is not valid with respect to its type, '#AnonType_langencodingcontrol'. _[data error]_

**Comment by rockivist** [comment]
@tcatapano I just made some fixes to address the issues you found with the undeprecated migration style sheets. In particular, I fixed the problems related to physfacet attributes, imprint/publisher, and unittitle/unitdate. I did not fix the issues related to bibref. I logged that issue in #50, not sure what can be done. It's not a problem with the schema, just the migration. But it's sufficiently complicated to unravel that I can live with it as is, at least until we hear from people that it's a serious issue.

If my fixes pass muster with another test, I'm happy to roll up to master.

**Comment by tcatapano** [comment]
@rockivist https://github.com/rockivist OK. I'll re-run the test of the
XSD/RNG undeprecated stylesheets. I also am in the midst of testing the DTD
valid undeprecated instances. Takes longer because it's a larger sample
size. Hope to have this done on Monday.

**Comment by tcatapano** [comment]
Testing EAD2002ToEAD3dtd_undeprecated.xsl 927 instances using xerces in oXygen 18 on Ubuntu 14.04
-     185 Description: Unexpected element "accessrestrict". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p),(accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-     108 Description: Attribute "langencoding" with value "iso639-2" must have a value from the list "iso639-1 iso639-2b iso639-3 otherlangencoding ". _[data error]_
-     106 Description: Unexpected element "prefercite". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p),(accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-      31 Description: Unexpected element "acqinfo". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p), (accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-      12 Description: Attribute value "" of type NMTOKEN must be a name token. _[error introduced by newer, stricter attribute models]_
-       9 Description: Unexpected element "userestrict". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p),(accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-       7 Description: The content of element type "controlaccess" is incomplete, it must match "(head?,(chronlist|list|table|blockquote|p|persname|corpname|famname|geogname|name|occupation|subject|genreform|function|title|controlaccess)+)". _[data error; source has no content only template PI]_
-       6 Description: Unexpected element "ref". The content of the parent element type must match "(abbr|expan|emph|lb|ptr|quote|num|footnote|date|persname|corpname|famname|geogname|name|occupation|subject|genreform|function|title)". _[ref inside ref from converted bibref]_
-       4 Description: Unexpected element "scopecontent". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p),(accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-       4 Description: Unexpected element "relatedmaterial". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p), (accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-       4 Description: Unexpected element "imprint". The content of the parent element type must match "(abbr|emph|expan|foreign|lb|ptr|ref|persname|corpname|famname|geogname|name|occupation|subject|genreform|function|title|date|footnote|num|quote)". _[known issue]_
-       4 Description: Unexpected element "bioghist". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p),(accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-       4 Description: Unexpected element "bibliography". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p),(accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-       4 Description: Unexpected element "altformavail". The content of the parent element type must match "(head?,((chronlist|list|table|blockquote|p),(accessrestrict|accruals|acqinfo|altformavail|appraisal|arrangement|bibliography|bioghist|controlaccess|custodhist|descgrp|fileplan|index|legalstatus|odd|originalsloc|otherfindaid|phystech|prefercite|processinfo|relatedmaterial|relations|scopecontent|separatedmaterial|userestrict))+)". _[looks like a DTD/schema error]_
-       3 Description: Unexpected element "imprint". The content of the parent element type must match "(abbr|expan|emph|lb|ptr|quote|num|footnote|date|persname|corpname|famname|geogname|name|occupation|subject|genreform|function|title)". _[known issue]_
-       2 Description: Unexpected element "ref". The content of the parent element type must match "((namegrp|persname|corpname|famname|geogname|name|occupation|subject|genreform|function|title),(ptrgrp|ptr|ref)?,indexentry*)". _[data error. no content as source has only template PI]_
-       2 Description: Attribute "countryencoding" with value "us" must have a value from the list "iso3166-1 othercountryencoding ". _[data error]_
-       1 Description: Attribute value "1972/1974" of type NMTOKEN must be a name token. _[error introduced by newer, stricter attribute models]_
-       1 Description: Attribute value "1966/1970" of type NMTOKEN must be a name token. _[error introduced by newer, stricter attribute models]_
-       1 Description: Attribute "scriptencoding" with value "iso-15924" must have a value from the list "iso15924 otherscriptencoding ". _[data error]_
-        1 Description: Attribute "langencoding" with value "iso6392b" must have a value from the list "iso639-1 iso639-2b iso639-3 otherlangencoding ". _[data error]_
-       1 Description: Attribute "langencoding" with value "iso-639-2b" must have a value from the list "iso639-1 iso639-2b iso639-3 otherlangencoding ". _[data error]_
-       1 Description: Attribute "actuate" with value "actuatenone" must have a value from the list "onload onrequest other none ". _[data error]_

**Comment by tcatapano** [comment]
@rockivist: current test of undeprecated dtd stylesheet reveals a probable error in the content model of descgrp. Im going to check against the rng and xsd to see if there's a problem there as well.

**Comment by tcatapano** [comment]
@rockivist: looks like the problem is only with the undeprecated DTD. Must have been some problem with the conversion from RNG to DTD by trang. I'll log an issue on the EAD3 repo.

**Comment by tcatapano** [comment]
@rockivist Nevermind, you already reported the bug (https://github.com/SAA-SDT/EAD3/issues/503) in the EAD3 repo

**Comment by tcatapano** [comment]
testing revised EAD2002ToEAD3schema_undeprecated.xsl on 650 EAD2002 valid instances using xerces in oXygen 18 on ubuntu 14.04:
- 17 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/undeprecated/":imprint}'. One of '{"http://ead3.archivists.org/schema/undeprecated/":abbr, "http://ead3.archivists.org/schema/undeprecated/":expan, "http://ead3.archivists.org/schema/undeprecated/":emph, "http://ead3.archivists.org/schema/undeprecated/":lb, "http://ead3.archivists.org/schema/undeprecated/":ptr, "http://ead3.archivists.org/schema/undeprecated/":quote, "http://ead3.archivists.org/schema/undeprecated/":num, "http://ead3.archivists.org/schema/undeprecated/":footnote, "http://ead3.archivists.org/schema/undeprecated/":date, "http://ead3.archivists.org/schema/undeprecated/":persname, "http://ead3.archivists.org/schema/undeprecated/":corpname, "http://ead3.archivists.org/schema/undeprecated/":famname, "http://ead3.archivists.org/schema/undeprecated/":geogname, "http://ead3.archivists.org/schema/undeprecated/":name, "http://ead3.archivists.org/schema/undeprecated/":occupation, "http://ead3.archivists.org/schema/undeprecated/":subject, "http://ead3.archivists.org/schema/undeprecated/":genreform, "http://ead3.archivists.org/schema/undeprecated/":function, "http://ead3.archivists.org/schema/undeprecated/":title}' is expected. _[known issue: imprint not valid as child of ref]_
-       3 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/undeprecated/":bibseries}'. One of '{"http://ead3.archivists.org/schema/undeprecated/":abbr, "http://ead3.archivists.org/schema/undeprecated/":expan, "http://ead3.archivists.org/schema/undeprecated/":emph, "http://ead3.archivists.org/schema/undeprecated/":lb, "http://ead3.archivists.org/schema/undeprecated/":ptr, "http://ead3.archivists.org/schema/undeprecated/":quote, "http://ead3.archivists.org/schema/undeprecated/":num, "http://ead3.archivists.org/schema/undeprecated/":footnote, "http://ead3.archivists.org/schema/undeprecated/":date, "http://ead3.archivists.org/schema/undeprecated/":persname, "http://ead3.archivists.org/schema/undeprecated/":corpname, "http://ead3.archivists.org/schema/undeprecated/":famname, "http://ead3.archivists.org/schema/undeprecated/":geogname, "http://ead3.archivists.org/schema/undeprecated/":name, "http://ead3.archivists.org/schema/undeprecated/":occupation, "http://ead3.archivists.org/schema/undeprecated/":subject, "http://ead3.archivists.org/schema/undeprecated/":genreform, "http://ead3.archivists.org/schema/undeprecated/":function, "http://ead3.archivists.org/schema/undeprecated/":title}' is expected._[known issue: bibseries not valid as child of ref]_
-       2 Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://ead3.archivists.org/schema/undeprecated/":ref}'. One of '{"http://ead3.archivists.org/schema/undeprecated/":abbr, "http://ead3.archivists.org/schema/undeprecated/":expan, "http://ead3.archivists.org/schema/undeprecated/":emph, "http://ead3.archivists.org/schema/undeprecated/":lb, "http://ead3.archivists.org/schema/undeprecated/":ptr, "http://ead3.archivists.org/schema/undeprecated/":quote, "http://ead3.archivists.org/schema/undeprecated/":num, "http://ead3.archivists.org/schema/undeprecated/":footnote, "http://ead3.archivists.org/schema/undeprecated/":date, "http://ead3.archivists.org/schema/undeprecated/":persname, "http://ead3.archivists.org/schema/undeprecated/":corpname, "http://ead3.archivists.org/schema/undeprecated/":famname, "http://ead3.archivists.org/schema/undeprecated/":geogname, "http://ead3.archivists.org/schema/undeprecated/":name, "http://ead3.archivists.org/schema/undeprecated/":occupation, "http://ead3.archivists.org/schema/undeprecated/":subject, "http://ead3.archivists.org/schema/undeprecated/":genreform, "http://ead3.archivists.org/schema/undeprecated/":function, "http://ead3.archivists.org/schema/undeprecated/":title}' is expected. _[known issue: ref not valid as child of ref]_
-       1 Description: cvc-enumeration-valid: Value 'iso939' is not facet-valid with respect to enumeration '[iso639-1, iso639-2b, iso639-3, otherlangencoding]'. It must be a value from the enumeration. _[data error]_
-       1 Description: cvc-complex-type.2.4.b: The content of element 'did' is not complete. One of '{"http://ead3.archivists.org/schema/undeprecated/":head, "http://ead3.archivists.org/schema/undeprecated/":abstract, "http://ead3.archivists.org/schema/undeprecated/":container, "http://ead3.archivists.org/schema/undeprecated/":dao, "http://ead3.archivists.org/schema/undeprecated/":daoset, "http://ead3.archivists.org/schema/undeprecated/":didnote, "http://ead3.archivists.org/schema/undeprecated/":langmaterial, "http://ead3.archivists.org/schema/undeprecated/":materialspec, "http://ead3.archivists.org/schema/undeprecated/":origination, "http://ead3.archivists.org/schema/undeprecated/":physdescset, "http://ead3.archivists.org/schema/undeprecated/":physdesc, "http://ead3.archivists.org/schema/undeprecated/":physdescstructured, "http://ead3.archivists.org/schema/undeprecated/":physloc, "http://ead3.archivists.org/schema/undeprecated/":repository, "http://ead3.archivists.org/schema/undeprecated/":unitdate, "http://ead3.archivists.org/schema/undeprecated/":unitdatestructured, "http://ead3.archivists.org/schema/undeprecated/":unitid, "http://ead3.archivists.org/schema/undeprecated/":unittitle}' is expected. _[note moved to odd leaves empty did]_
-       1 Description: cvc-attribute.3: The value 'iso939' of attribute 'langencoding' on element 'control' is not valid with respect to its type, '#AnonType_langencodingcontrol'. _[data error]_

**Comment by tcatapano** [comment]
@rockivist: xsd/rng converter give the same errors, none of which is a bug. Given that, aside from the DTD bug, the DTD stylesheet seems to also have no bugs, I'd say we're ready to merge. Do you agree?

**Comment by rockivist** [comment]
Absolutely! Go for it!

**Comment by rockivist** [comment]
@tcatapano Thanks! Will you put together a new release? As soon as that is done I'll post an announcement.

**Comment by tcatapano** [comment]
@rockivist: draft release has been prepared. Take a look before it is
published.
https://github.com/SAA-SDT/EAD2002toEAD3/releases/tag/untagged-cdbae7f61f8614016083

**Comment by rockivist** [comment]
@tcatapano I added a link to issues since a few are known. Otherwise it looks good. Will you keep this pre-release or will this graduate out of beta? I'm happy to make it a full release since I think it's about as good as its going to get.

**Comment by tcatapano** [comment]
@rockivist: I was going to go ahead and make this 1.0.0. Just released it:

https://github.com/SAA-SDT/EAD2002toEAD3/releases/tag/v1.0.0

Congrats!

/Terry

**Comment by rockivist** [comment]
@tcatapano Awesome! Thanks so much. A drink to celebrate sometime soon is necessary.

**Pull request merged**
